### ISSUE TITLE
My boards -> Action "voir"

### ISSUE THREAD

**Issue by aronAB-a** [Alexcimad/surf-buddy-rental#71]
Quand je suis sur le profil d'Alexis, que je vais dans l'onglet "My boards", et que je souhaite faire l'action "Voir" j'ai cette erreur -> OffersController#show is missing a template for this request format and variant. request.formats: ["text/html"] request.variant: []

**Comment by Alexcimad** [comment]
Yes, Théo est sur le sujet 👍

**Comment by Alexcimad** [comment]
Bug corrected
