### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by aronAB-a** [Alexcimad/surf-buddy-rental#79]
- Changer le format des dates
- Remplacer "jour" par "day" dans la liste des offers
- Bouton "delete this offer" à mettre en rouge
- Dans la modal, redondance de la croix et de close
- Le bouton "confirm booking" et le champ date sont collés
- Remplacer "create offer" par "Add a board"
- Ajouter des picto pour le prix notamment pour le price per day quand on créé une offer

**Comment by Alexcimad** [comment]
Done
